title: "Wilmer Arley — Perfil de Desarrollador"
description: "Aprendiendo desarrollo con Python. Enfocado en construir soluciones eficientes desde Madrid."
author: "Wilmer Arley"
github_username: wiilmerarleii
linkedin_username: wilmerzlizarazo

theme: minima
lang: "es-ES"
timezone: "Europe/Madrid"
